
#[all]
#k8s-node-1 ansible_user=jnewson ansible_ssh_private_key_file=~/.ssh/id_rsa.kubespray ansible_host=10.0.1.36 etcd_member_name=etcd1
#k8s-node-2 ansible_user=jnewson ansible_ssh_private_key_file=~/.ssh/id_rsa.kubespray ansible_host=10.0.1.37 etcd_member_name=etcd2
#k8s-node-3 ansible_user=jnewson ansible_ssh_private_key_file=~/.ssh/id_rsa.kubespray ansible_host=10.0.1.38 etcd_member_name=etcd3

#[kube_control_plane]
#k8s-node-1
#k8s-node-2
#k8s-node-3

#[etcd]
#k8s-node-1
#k8s-node-2
#k8s-node-3

#[kube_node]
#k8s-node-1
#k8s-node-2
#k8s-node-3

#[k8s_cluster:children]
#kube_control_plane
#kube_node
